# -*- coding: utf-8 -*-
"""extracción de métricas .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvR6Uhrmuc-k647hU8chWf57dvVBQuvA
"""

import pandas as pd
import json

# Ruta al archivo que se ve en tu imagen
file_path = 'catboost_training.json'

with open(file_path, 'r') as f:
    data = json.load(f)

# Extraer las métricas de cada iteración
# Dependiendo de la versión, las métricas están en 'iterations'
iterations = data['iterations']

# Creamos una lista de diccionarios para cargar en Pandas
rows = []
for iter_data in iterations:
    row = {
        'iteration': iter_data['iteration'],
        'learn_loss': iter_data['learn'][0] # El primer valor suele ser la función objetivo (RMSE/Logloss)
    }
    # Si tienes métricas de validación (test), aparecerán aquí:
    if 'test_sets' in iter_data:
        row['test_loss'] = iter_data['test_sets'][0][0]

    rows.append(row)

df_metrics = pd.DataFrame(rows)

print("Primeras filas de las métricas:")
print(df_metrics.head())

# Graficar para ver si el modelo aprendió bien
df_metrics.set_index('iteration').plot(title="Progreso del Entrenamiento")

import matplotlib.pyplot as plt

# Aquí pones los nombres de los modelos que usaron
modelos = ['CatBoost', 'Modelo B', 'Modelo C']

# Aquí pones el error final de cada uno (entre más bajo, mejor)
# El de CatBoost ya lo tienes (es el último punto de la gráfica que hiciste)
errores = [1.25, 1.42, 1.38]

plt.figure(figsize=(8, 5))
plt.bar(modelos, errores, color=['blue', 'gray', 'gray'])
plt.title('Comparación de Modelos (Error Final)')
plt.ylabel('Error (Loss)')
plt.show()